export default {
    REGISTER_ACTION: 'REGISTER_ACTION',
    REGISTER_ACTION_REQUEST: 'REGISTER_ACTION_REQUEST',
    REGISTER_ACTION_SUCCESS: 'REGISTER_ACTION_SUCCESS',
    REGISTER_ACTION_ERROR: 'REGISTER_ACTION_ERROR',
    LOGIN_ACTION: 'LOGIN_ACTION',
    LOGIN_ACTION_REQUEST: 'LOGIN_ACTION_REQUEST',
    LOGIN_ACTION_SUCCESS: 'LOGIN_ACTION_SUCCESS',
    LOGIN_ACTION_ERROR: 'LOGIN_ACTION_ERROR',
    CHECK_TOKEN_ACTION: 'CHECK_TOKEN_ACTION',
    CHECK_TOKEN_ACTION_REQUEST: 'CHECK_TOKEN_ACTION_REQUEST',
    CHECK_TOKEN_ACTION_SUCCESS: 'CHECK_TOKEN_ACTION_SUCCESS',
    CHECK_TOKEN_ACTION_ERROR: 'CHECK_TOKEN_ACTION_ERROR'
}