export default {
    REGISTER_ACTION: 'REGISTER_ACTION',
    REGISTER_ACTION_REQUEST: 'REGISTER_ACTION_REQUEST',
    REGISTER_ACTION_SUCCESS: 'REGISTER_ACTION_SUCCESS',
    REGISTER_ACTION_ERROR: 'REGISTER_ACTION_ERROR'
}